//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DicentDraw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dessert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dessert()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public string DessertID { get; set; }
        public string DessertName { get; set; }
        public int DessertPrice { get; set; }
        public string DessertKind { get; set; }
        public string DessertIntroduction { get; set; }
        public string DessertImage { get; set; }
        public bool IsOnSale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
