//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DicentDraw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public string DetailID { get; set; }
        public int DessertAmount { get; set; }
        public string OrderID { get; set; }
        public string GiftID { get; set; }
        public string DessertID { get; set; }
    
        public virtual Dessert Dessert { get; set; }
        public virtual Gift Gift { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
